export const dogs = [
  {
    id: 1,
    name: "Anton",
    race: "Shepard Labrador Mix",
    birthdate: "14.07.2014",
    birthplace: "Romania",
    sex: "male",
    color: "black",
    transponder: "900062000093618",
    vaccinations: "none",
    insurances: "none",
  },
  {
    id: 2,
    name: "Canella",
    birthdate: "01.05.2018",
    birthplace: "Spain",
    sex: "female",
    color: "brown",
    race: "Unknown Mix",
    vaccinations: "none",
    insurances: "none",
    transponder: "unknown",
  },
];
